stages:
  - build
  - test

checkpatch-job:
  stage: build
  image: $DOCKER_IMAGE
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  script:
    - echo "Welcome, $GITLAB_USER_LOGIN!"
    - set -e exec
    - exec git diff $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | ~/zephyrproject/zephyr/scripts/checkpatch.pl -q
  tags:
    - docker
  except:
    changes:
      - .gitlab-ci.yml
      - "*.sh"

.build-all-job:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - cd ~/zephyrproject/zephyr
    - git remote add ci20_zephyr $CI20_ZEPHYR_REPO_URL
    - git remote update
    - git checkout $BRANCH_NAME
    - git rebase --onto $BRANCH_NAME HEAD
    - git pull
    - cd ..
    - git clone $NPCX_TEST_REPO_URL
    - cd ~/zephyrproject
    - west update
    - cd ~/zephyrproject/npcx_tests
    - chmod a+x ./check_overlay.sh
    - ./check_overlay.sh $BOARD_NAME $MODULE_NAME
    - rm -rf ~/zephyrproject/npcx_tests
  tags:
    - docker
  artifacts:
    when: always
    paths:
     - $CI_PROJECT_DIR/
    expire_in: 1 week

build-k3-job:
  extends: .build-all-job
  parallel:
      matrix:
        - BRANCH_NAME: "npcx_k3_1025"
          BOARD_NAME: "npck3m7k_evb"
          MODULE_NAME: ["adc", "adc_cmp", "bbram", "espi", "espisaf", "gpio", "gpio_all_io_test", "kscan", "miwu_auto_test", "nor_flash", "peci", "ps2", "pwm", "sha", "smbm", "smbm_tmp100", "smbs", "tach"]
  only:
    refs:
      - master
      - triggers
build-x9-job:
  extends: .build-all-job
  parallel:
      matrix:
        - BRANCH_NAME: "main"
          BOARD_NAME: "npcx9m6f_evb"
          MODULE_NAME: ["adc", "adc_cmp", "bbram", "espi", "espisaf", "gpio", "gpio_all_io_test", "kscan", "miwu_auto_test", "nor_flash", "peci", "ps2", "pwm", "sha", "smbm", "smbm_tmp100", "smbs", "tach"]
  only:
    refs:
      - master
      - triggers